### ISSUE TITLE
Unknown Error: Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET

### ISSUE THREAD

**Issue by tdog41** [theSkyseS/Engarde-Synthesis-Patcher#14]
Hey guys,

I'm getting this error when I try to add the patcher to Synthesis:

Unknown Error: Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
[log-20210321.txt](https://github.com/theSkyseS/Engarde-Synthesis-Patcher/files/6178573/log-20210321.txt)

Edit. I have both Synthesis and .NET latest versions installed.

Cheers

**Comment by tdog41** [comment]
I was using the Profile versions for Mutagen and Synthesis.
Changing to Latest fixed the issue.

Cheers

**Comment by theSkyseS** [comment]
Yeah, Mutagen and Synthesis are in active development, so this kind of issues can often occur. Standart steps for solving issues like this:

1. Make sure that you are using latest version of Synthesis GUI and versions set to "Latest"
2. If "Latest" version does not work, you can try to set version to "Match"
