### ISSUE TITLE
Bows and crossbows are not being patched

### ISSUE THREAD

**Issue by zhongjiedong** [theSkyseS/Engarde-Synthesis-Patcher#20]
Bows do not seem to get the "MCT_WeakAgainstArmored [KYWD:BF0E3805]" keyword and crossbows are not getting the "MCT_PenetratesArmorKW [KYWD:BF281901]" keyword apart from a few unique weapons.

You just end up with a bunch of ITPO for the two weapon types

**Comment by theSkyseS** [comment]
Interesting, this don't happens on vanilla sse profile. Can you screenshoot bow or crossbow record in xEdit(sseedit)?

**Comment by theSkyseS** [comment]
I close it for now, due to your inactivity. Feel free to reopen.

**Comment by zhongjiedong** [comment]
my bad, was busy until the weekend, here's a screenshot of a ton of bows missing keywords:

![2021-04-17 19_47_47-](https://user-images.githubusercontent.com/20669755/115123638-e7b18580-9fb5-11eb-8219-0bde4caeace5.png)

**Comment by theSkyseS** [comment]
Ah, okay let me explain:
Enchanted weapons using their unenchanted versions as templates which fills the stats like stats and keywords. So patcher just ignores weapons that use templates. You can notice, that all enchanted weapons are untouched.
As for why it goes into Synthesis output I don't really know. Perhaps, another pathcer touches it?

**Comment by theSkyseS** [comment]
As for ITPOs, I can only that Engarde patcher don't touch weapons that using template, so it's can be another patcher if you use them.

**Comment by zhongjiedong** [comment]
I see, is this something that can be considered as a feature request?

**Comment by theSkyseS** [comment]
Wait, what feature do you want to request?
There's no need to patch enchanted weapons, because they take their stats from templates, which are already patched.
