### ISSUE TITLE
Blacklist enchanted weapons

### ISSUE THREAD

**Issue by zhongjiedong** [theSkyseS/Engarde-Synthesis-Patcher#36]
Hey, just wondering if Engarde should be patching enchanted versions of weapons since they use a template anyway?

**Comment by theSkyseS** [comment]
Is shouldn't. And if I remember it correctly it doesn't

**Comment by zhongjiedong** [comment]
hmm then it is the other patcher probably either keywords or speed and reach thanks for checking
